package com.redhat.topicindex.entity;

// Generated Jun 8, 2011 1:12:46 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * IntegerConstants generated by hbm2java
 */
@Entity
@Audited
@Table(name = "IntegerConstants", catalog = "Skynet")
public class IntegerConstants implements java.io.Serializable 
{
	private static final long serialVersionUID = -6660808431652587223L;
	private Integer integerConstantsId;
	private String constantName;
	private Integer constantValue;

	public IntegerConstants() {
	}

	public IntegerConstants(String constantName) {
		this.constantName = constantName;
	}

	public IntegerConstants(String constantName, Integer constantValue) {
		this.constantName = constantName;
		this.constantValue = constantValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IntegerConstantsID", unique = true, nullable = false)
	public Integer getIntegerConstantsId() {
		return this.integerConstantsId;
	}

	public void setIntegerConstantsId(Integer integerConstantsId) {
		this.integerConstantsId = integerConstantsId;
	}

	@Column(name = "ConstantName", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getConstantName() {
		return this.constantName;
	}

	public void setConstantName(String constantName) {
		this.constantName = constantName;
	}

	@Column(name = "ConstantValue")
	public Integer getConstantValue() {
		return this.constantValue;
	}

	public void setConstantValue(Integer constantValue) {
		this.constantValue = constantValue;
	}

}
