package com.redhat.topicindex.entity;

// Generated Aug 11, 2011 2:31:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.validator.Length;

/**
 * RoleToRoleRelationship generated by hbm2java
 */
@Entity
@Audited
@Table(name = "RoleToRoleRelationship")
public class RoleToRoleRelationship implements java.io.Serializable 
{
	private static final long serialVersionUID = -5070074888185753060L;
	private Integer roleToRoleRelationshipId;
	private String description;
	private Set<RoleToRole> roleToRoles = new HashSet<RoleToRole>(0);

	public RoleToRoleRelationship() {
	}

	public RoleToRoleRelationship(String description,
			Set<RoleToRole> roleToRoles) {
		this.description = description;
		this.roleToRoles = roleToRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RoleToRoleRelationshipID", unique = true, nullable = false)
	public Integer getRoleToRoleRelationshipId() {
		return this.roleToRoleRelationshipId;
	}

	public void setRoleToRoleRelationshipId(Integer roleToRoleRelationshipId) {
		this.roleToRoleRelationshipId = roleToRoleRelationshipId;
	}

	//@Column(name = "Description", length = 65535)
	@Column(name = "Description", columnDefinition="TEXT")
	@Length(max = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleToRoleRelationship")
	public Set<RoleToRole> getRoleToRoles() {
		return this.roleToRoles;
	}

	public void setRoleToRoles(Set<RoleToRole> roleToRoles) {
		this.roleToRoles = roleToRoles;
	}

}
