package com.redhat.topicindex.entity;

// Generated Nov 10, 2011 6:05:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Exception generated by hbm2java
 */
@Entity
@Table(name = "Exception")
public class SkynetException implements java.io.Serializable
{
	private static final long serialVersionUID = 3433948802907020258L;
	private Integer exceptionId;
	private Date timestamp;
	private String details;
	private boolean expected;
	private String description;

	public SkynetException()
	{
	}

	public SkynetException(final String details, final boolean expected)
	{
		this.details = details;
		this.expected = expected;
	}

	public SkynetException(final String details, final boolean expected, final String description)
	{
		this.details = details;
		this.expected = expected;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ExceptionID", unique = true, nullable = false)
	public Integer getExceptionId()
	{
		return this.exceptionId;
	}

	public void setExceptionId(Integer exceptionId)
	{
		this.exceptionId = exceptionId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Timestamp", nullable = false, length = 19)
	@NotNull
	public Date getTimestamp()
	{
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp)
	{
		this.timestamp = timestamp;
	}

	@Column(name = "Details", nullable = false, length = 65535)
	@NotNull
	@Length(max = 65535)
	public String getDetails()
	{
		return this.details;
	}

	public void setDetails(String details)
	{
		this.details = details;
	}

	@Column(name = "Expected", nullable = false)
	public boolean isExpected()
	{
		return this.expected;
	}

	public void setExpected(boolean expected)
	{
		this.expected = expected;
	}

	@Column(name = "Description", length = 65535)
	@Length(max = 65535)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}
	
	@PrePersist
	private void prePersist()
	{
		this.timestamp = new Date();
	}

}
